"""Stage the patcher's inputs from the rest of the repository.

The patcher is frozen into one exe, so it carries copies of things that live
elsewhere in this repo: the offset resolver and the unpacker (tools/), the mod
host and the shipped mods (mods/), the native registry, and the stub DLL once
you have built it (stub/). Those copies are GENERATED by this script and never
edited by hand - a fix made in one copy and not the other is a silent wrong-
address bug, which is exactly the class of bug this whole project exists to
avoid.

    python sync.py            copy everything into src/triarch_patcher/
    python sync.py --check    exit 1 if any copy is stale (use it in CI)

build.bat runs it before freezing.
"""
import hashlib
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PKG = os.path.join(HERE, "src", "triarch_patcher")
VENDOR = os.path.join(PKG, "vendor")
RES = os.path.join(PKG, "resources")

TOOLS = ["mkoffsets.py", "namemods.py", "unuriel.py", "ksattack.py", "imports_db.json"]
MODS_SKIP = {"__pycache__"}


def _files_under(root):
    out = {}
    for d, dirs, files in os.walk(root):
        dirs[:] = [x for x in dirs if x not in MODS_SKIP]
        for f in files:
            if f.endswith((".pyc", ".pyo")):
                continue
            p = os.path.join(d, f)
            out[os.path.relpath(p, root)] = open(p, "rb").read()
    return out


def plan():
    """(destination, bytes) for every file the package should contain."""
    want = {os.path.join(VENDOR, "__init__.py"): b""}
    for name in TOOLS:
        want[os.path.join(VENDOR, name)] = open(os.path.join(ROOT, "tools", name), "rb").read()
    mods = os.path.join(ROOT, "mods")
    for rel, data in _files_under(mods).items():
        want[os.path.join(RES, "mods", rel)] = data
    want[os.path.join(RES, "natives.json")] = open(os.path.join(mods, "natives.json"), "rb").read()
    dll = os.path.join(ROOT, "stub", "uriel_stub.dll")
    if os.path.isfile(dll):
        blob = open(dll, "rb").read()
        want[os.path.join(RES, "uriel_stub.dll")] = blob
        want[os.path.join(RES, "uriel_stub.dll.sha256")] = hashlib.sha256(blob).hexdigest().encode()
    return want


def mod_folders():
    """Top-level mod folders under mods/. Everything here ships AND loads
    (the host enables a mod with no config section by default), so say
    what is being bundled rather than staging whatever happens to be there."""
    mods = os.path.join(ROOT, "mods")
    return sorted(d for d in os.listdir(mods)
                  if os.path.isfile(os.path.join(mods, d, "main.py")))


def main():
    want = plan()
    check = "--check" in sys.argv
    folders = mod_folders()
    print("bundling %d mod folder(s): %s" % (len(folders), ", ".join(folders)))
    stale = []
    for dst, data in sorted(want.items()):
        have = open(dst, "rb").read() if os.path.isfile(dst) else None
        if have == data:
            continue
        stale.append(os.path.relpath(dst, HERE))
        if not check:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            with open(dst, "wb") as f:
                f.write(data)
    # remove mods that were deleted upstream, so a dropped mod does not ship
    if os.path.isdir(os.path.join(RES, "mods")):
        for rel in _files_under(os.path.join(RES, "mods")):
            dst = os.path.join(RES, "mods", rel)
            if dst not in want:
                stale.append(os.path.relpath(dst, HERE) + " (orphan)")
                if not check:
                    os.remove(dst)
    if check:
        if stale:
            print("STALE:\n  " + "\n  ".join(stale))
            sys.exit(1)
        print("package inputs are up to date (%d files)" % len(want))
    else:
        print("synced %d file(s), %d changed" % (len(want), len(stale)))
        if not os.path.isfile(os.path.join(ROOT, "stub", "uriel_stub.dll")):
            print("note: stub/uriel_stub.dll not built yet - run build.bat stub first "
                  "or the patcher will have no DLL to deploy")


if __name__ == "__main__":
    main()
